development: &default
  adapter: postgresql
  database: gosalyn_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test: &test
  <<: *default
  database: gosalyn_test

cucumber:
  <<: *test